# src/blog_writer/config/tasks.yaml

topic_analysis_task:
  description: >
    Perform a strategic analysis of the blog post topic: '{topic}' with the desired writing tone: '{tone}'.
    1. Identify the most likely **Target Audience** (e.g., 'Technical Beginners', 'Marketing Professionals', 'General Consumers').
    2. Define a single, concise **Key Takeaway Message** the reader should remember.
    3. Develop a logical outline of 3-5 **Engaging H2 Sub-headings** that cover the topic comprehensively for the identified audience.
    Structure the output as a JSON string containing keys: "target_audience", "key_takeaway", and "outline_headings" (list of strings).
  expected_output: >
    A JSON string representing a dictionary with the analysis results.
    Example:
    '{{"target_audience": "Beginners interested in AI", "key_takeaway": "Generative AI offers accessible tools that can enhance creativity and productivity in everyday life.", "outline_headings": ["What Exactly is Generative AI?", "Fun Ways AI Can Boost Your Creativity", "Making Daily Chores Easier with AI", "Cool AI Tools You Can Try Today", "The Friendly Future with AI"]}}'
  agent: topic_analyzer

research_task:
  description: >
    Conduct targeted research for the blog post on '{topic}'.
    Use the context provided by the 'topic_analysis_task' to understand the specific **sub-topics (outline_headings)** and the identified **target_audience**.
    1. Using the News Search Tool, find 2-3 recent (2024-2025, or relevant historical context if appropriate for the topic) and highly relevant news updates related to '{topic}'. Briefly summarize each and explain its significance.
    2. Using the Keyword Finder Tool, generate a list of 10-15 relevant semantic keywords and phrases, considering search intent for the **target_audience identified in the context**.
    Compile these findings into a clearly structured report using Markdown headings (### News Highlights, ### Relevant Keywords). Ensure conciseness and relevance.
  expected_output: >
    A single string containing the structured research report.
    Example format:
    "### News Highlights\n- **Article 1 Title (Date):** Summary explaining relevance...\n- **Article 2 Title (Date):** Summary explaining relevance...\n\n### Relevant Keywords\n- keyword1\n- keyword 2\n..."
  agent: researcher
  context:
    - topic_analysis_task

writing_task:
  description: >
    Write a complete, high-quality, and engaging blog post about '{topic}' using a professional '{tone}'.
    **Reference the context from 'topic_analysis_task' extensively:**
    1.  Write specifically for the **target_audience identified in the context**.
    2.  Structure the post precisely using the **H2 outline_headings provided in the context**.
    **Strictly follow these instructions:**
    3.  Address the needs and understanding level of the target audience.
    4.  Naturally integrate insights from the 'research_task' context (news relevance, keywords). Avoid forced keyword stuffing; aim for organic inclusion.
    5.  Craft a compelling introduction that grabs attention and clearly states the post's purpose.
    6.  Develop each section (~250-350 words) with valuable information, ensuring logical flow and smooth transitions. Use varied sentence structures.
    7.  Subtly incorporate the **key_takeaway message identified in the context** throughout the post and emphasize it in the conclusion.
    8.  Use Markdown formatting (bold, lists, etc.) to enhance readability. Proofread carefully for grammar and spelling errors.
    9.  Conclude with a strong summary and a clear, relevant call-to-action.
    **CRITICAL: The output MUST be the blog post content ONLY, formatted strictly in Markdown. NO introduction like "Here is the blog post:", comments, or any other text.**
  expected_output: >
    A single string containing the full, well-structured, and engaging blog post in Markdown format, ready for publishing. Starts with the H1 or first paragraph, ends with the last line of the conclusion/CTA.
  agent: writer
  context:
    - topic_analysis_task
    - research_task

seo_optimization_task:
  description: >
    Analyze the final blog post content (from 'writing_task' context) for '{topic}'.
    Generate optimized SEO metadata designed for maximum search visibility and click-through rate (CTR).
    1.  **Title:** Craft a compelling, SEO-friendly title (ideally under 60 chars).
    2.  **Meta Description:** Write an engaging meta description (MAX 160 chars) summarizing the value and encouraging clicks.
    3.  **Tags/Keywords:** Identify and list 5-7 highly relevant tags/keywords based on content and research context.
    4.  **URL Slug:** Create a short, descriptive, lowercase, kebab-case URL slug.
    **Output Format:** Return ONLY a valid JSON string containing the keys "title", "meta_description", "tags" (list of strings), and "slug".
  expected_output: >
    A JSON string representing the optimized SEO metadata.
    Example:
    '{{"title": "Generative AI in Daily Life: Easy Tools & Tips (2025)", "meta_description": "Discover how friendly Generative AI tools can boost your creativity and simplify everyday tasks. Learn easy ways to get started with AI today!", "tags": ["generative ai", "ai tools", "everyday ai", "ai productivity", "creative ai", "beginner ai guide", "ai trends 2025"], "slug": "generative-ai-daily-life-tools-tips"}}'
  agent: seo_optimizer
  context:
    - writing_task
    - research_task